-- GENERATED by tools/semantic_layer.py from databricks/semantic/revenue/category_mix.yaml — do not edit;
-- edit the YAML definition and run `python tools/semantic_layer.py generate`.
-- Executed by the semantic_layer bundle job, which binds :catalog to
-- ${var.catalog}; unqualified gold.* / silver.* sources resolve in that catalog.
USE CATALOG IDENTIFIER(:catalog);

CREATE OR REPLACE VIEW semantic.category_mix_metrics
WITH METRICS
LANGUAGE YAML
AS $$
# Legacy: legacy/redshift/units/category_mix/report.sql
#   SELECT category, units_sold, revenue, revenue_share FROM mart.category_mix ORDER BY revenue DESC
version: 1.1
comment: Units, revenue and revenue share per product category (gold.category_mix, one row per category).
source: gold.category_mix
dimensions:
  - name: category
    expr: category
measures:
  - name: units_sold
    expr: SUM(units_sold)
  - name: revenue
    expr: SUM(revenue)
  - name: revenue_share
    expr: SUM(revenue_share)
    comment: >-
      Category share of total revenue, precomputed in the mart as
      ROUND(revenue / SUM(revenue) OVER (), 4) - additive across categories.
$$;
