-- GENERATED by tools/semantic_layer.py from databricks/semantic/customer/churn_flags.yaml — do not edit;
-- edit the YAML definition and run `python tools/semantic_layer.py generate`.
-- Executed by the semantic_layer bundle job, which binds :catalog to
-- ${var.catalog}; unqualified gold.* / silver.* sources resolve in that catalog.
USE CATALOG IDENTIFIER(:catalog);

CREATE OR REPLACE VIEW semantic.churn_flags_metrics
WITH METRICS
LANGUAGE YAML
AS $$
# Legacy: legacy/redshift/units/churn_flags/report.sql
#   SELECT churn_flag, COUNT(*) AS customers, AVG(days_since_order) AS avg_days_since_order
#   FROM mart.churn_flags GROUP BY churn_flag
# days_since_order and churn_flag are computed in the ETL against the fixed
# '2025-12-31' anchor (never CURRENT_DATE).
version: 1.1
comment: Customer churn status as of the fixed 2025-12-31 anchor (gold.churn_flags).
source: gold.churn_flags
dimensions:
  - name: customer_id
    expr: customer_id
  - name: churn_flag
    expr: churn_flag
    comment: Churn bucket from days since the last order before the 2025-12-31 anchor.
  - name: last_order_date
    expr: last_order_date
measures:
  - name: customers
    expr: COUNT(1)
  - name: avg_days_since_order
    expr: CAST(SUM(days_since_order) DIV COUNT(days_since_order) AS BIGINT)
    comment: Redshift AVG over an integer column is integer (truncating) division.
$$;
