-- GENERATED by tools/semantic_layer.py from databricks/semantic/revenue/geo_rollup.yaml — do not edit;
-- edit the YAML definition and run `python tools/semantic_layer.py generate`.
-- Executed by the semantic_layer bundle job, which binds :catalog to
-- ${var.catalog}; unqualified gold.* / silver.* sources resolve in that catalog.
USE CATALOG IDENTIFIER(:catalog);

CREATE OR REPLACE VIEW semantic.geo_rollup_metrics
WITH METRICS
LANGUAGE YAML
AS $$
# Legacy: legacy/redshift/units/geo_rollup/report.sql
#   SELECT grouping_id, region, state, order_count, revenue FROM mart.geo_rollup
#   ORDER BY grouping_id, region NULLS FIRST, state NULLS FIRST
version: 1.1
comment: >-
  Orders and revenue by customer region/state ROLLUP (gold.geo_rollup). Each rollup level is a
  separate row set - always filter or group by grouping_id to avoid double counting.
source: gold.geo_rollup
dimensions:
  - name: grouping_id
    expr: grouping_id
    comment: GROUPING(region, state) bitmask - 0 = region x state, 1 = region subtotal, 3 = grand total.
  - name: grouping_level
    expr: CASE grouping_id WHEN 0 THEN 'state' WHEN 1 THEN 'region' WHEN 3 THEN 'total' END
  - name: region
    expr: region
    comment: Customer region - NULL on the grand-total row.
  - name: state
    expr: state
    comment: Customer state - NULL on subtotal and grand-total rows.
measures:
  - name: order_count
    expr: SUM(order_count)
  - name: revenue
    expr: SUM(revenue)
$$;
