-- GENERATED by tools/semantic_layer.py from databricks/semantic/revenue/product_perf.yaml — do not edit;
-- edit the YAML definition and run `python tools/semantic_layer.py generate`.
-- Executed by the semantic_layer bundle job, which binds :catalog to
-- ${var.catalog}; unqualified gold.* / silver.* sources resolve in that catalog.
USE CATALOG IDENTIFIER(:catalog);

CREATE OR REPLACE VIEW semantic.product_perf_metrics
WITH METRICS
LANGUAGE YAML
AS $$
# Legacy: legacy/redshift/units/product_perf/report.sql
#   SELECT category, COUNT(*) AS products, SUM(units_sold) AS units_sold, SUM(revenue) AS revenue
#   FROM mart.product_perf GROUP BY category
version: 1.1
comment: Product-level units sold and revenue (gold.product_perf, one row per product).
source: gold.product_perf
dimensions:
  - name: product_id
    expr: product_id
  - name: category
    expr: category
  - name: top_stores
    expr: top_stores
    comment: LISTAGG of the product's top stores (legacy ETL).
measures:
  - name: products
    expr: COUNT(1)
    comment: Number of products (one mart row per product).
  - name: units_sold
    expr: SUM(units_sold)
  - name: revenue
    expr: SUM(revenue)
$$;
