-- GENERATED by tools/semantic_layer.py from databricks/semantic/manifest.yaml — do not edit;
-- edit the YAML definition and run `python tools/semantic_layer.py generate`.
-- Executed by the semantic_layer bundle job, which binds :catalog to
-- ${var.catalog}; unqualified gold.* / silver.* sources resolve in that catalog.
USE CATALOG IDENTIFIER(:catalog);

CREATE SCHEMA IF NOT EXISTS semantic
COMMENT 'Governed Unity Catalog metric views over the migrated gold.* marts (legacy Redshift report.sql business rules)';
