-- GENERATED by tools/semantic_layer.py from databricks/semantic/operations/shipping_sla.yaml — do not edit;
-- edit the YAML definition and run `python tools/semantic_layer.py generate`.
-- Executed by the semantic_layer bundle job, which binds :catalog to
-- ${var.catalog}; unqualified gold.* / silver.* sources resolve in that catalog.
USE CATALOG IDENTIFIER(:catalog);

CREATE OR REPLACE VIEW semantic.shipping_sla_metrics
WITH METRICS
LANGUAGE YAML
AS $$
# Legacy: legacy/redshift/units/shipping_sla/report.sql
#   SELECT carrier, shipments, delivered, in_flight, avg_hours_to_deliver,
#          max_hours_to_deliver, on_time_96h FROM mart.shipping_sla
version: 1.1
comment: >-
  Shipping SLA per carrier (gold.shipping_sla, one row per carrier). Hours use Redshift
  DATEDIFF(hour) boundary semantics from the ETL - on-time = delivered within 96 hours.
source: gold.shipping_sla
dimensions:
  - name: carrier
    expr: carrier
measures:
  - name: shipments
    expr: SUM(shipments)
  - name: delivered
    expr: SUM(delivered)
  - name: in_flight
    expr: SUM(in_flight)
  - name: avg_hours_to_deliver
    expr: CASE WHEN COUNT(1) = 1 THEN MAX(avg_hours_to_deliver) END
    comment: Integer average hours per carrier - NULL when more than one carrier is aggregated.
  - name: max_hours_to_deliver
    expr: MAX(max_hours_to_deliver)
  - name: on_time_96h
    expr: SUM(on_time_96h)
  - name: earliest_local_delivery_hour
    expr: MIN(earliest_local_delivery_hour)
$$;
