"""Unity Catalog semantic layer: metric views over the migrated gold.* marts.

    python tools/semantic_layer.py generate          # write DDL + DAB job from the manifest
    python tools/semantic_layer.py generate --check  # fail if generated files are stale/invalid
    python tools/semantic_layer.py deploy [--view V] # CREATE OR REPLACE the views via a SQL warehouse

Source of truth: databricks/semantic/manifest.yaml plus one metric-view YAML
definition per business subject under databricks/semantic/<group>/. `generate`
renders each definition into databricks/semantic/ddl/<view>.sql
(CREATE OR REPLACE VIEW semantic.<view> WITH METRICS LANGUAGE YAML) and the
databricks/resources/semantic_layer.job.yml bundle job that executes those files.
`deploy` runs the same DDL directly against DATABRICKS_WAREHOUSE_ID / MIG_CATALOG.
"""
import argparse
import json
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from validation.dbsql import DbSql

SEMANTIC_DIR = ROOT / "databricks" / "semantic"
SEMANTIC_MANIFEST = SEMANTIC_DIR / "manifest.yaml"
DDL_DIR = SEMANTIC_DIR / "ddl"
JOB_RESOURCE = ROOT / "databricks" / "resources" / "semantic_layer.job.yml"
UNITS_MANIFEST = ROOT / ".migration" / "units.yaml"
ALLOWED_TARGETS = ROOT / ".migration" / "allowed_targets.json"
APPROVED_CATALOGS = {"mig_redshift_dev", "mig_redshift"}
SCHEMA_TASK = "semantic_schema"

DDL_HEADER = """-- GENERATED by tools/semantic_layer.py from {source} — do not edit;
-- edit the YAML definition and run `python tools/semantic_layer.py generate`.
-- Executed by the semantic_layer bundle job, which binds :catalog to
-- ${{var.catalog}}; unqualified gold.* / silver.* sources resolve in that catalog.
USE CATALOG IDENTIFIER(:catalog);

"""


def loadYaml(path):
    with open(path) as f:
        return yaml.safe_load(f)


def loadManifest(path=SEMANTIC_MANIFEST):
    return loadYaml(path)


def definitionPath(spec):
    return SEMANTIC_DIR / spec["definition"]


def definitionText(spec):
    return definitionPath(spec).read_text()


def schemaStatement(schema):
    return (
        f"CREATE SCHEMA IF NOT EXISTS {schema}\n"
        "COMMENT 'Governed Unity Catalog metric views over the migrated gold.* marts "
        "(legacy Redshift report.sql business rules)'"
    )


def viewStatement(schema, name, spec):
    body = definitionText(spec).rstrip("\n")
    if "$$" in body or ";" in body:
        raise ValueError(f"{spec['definition']} must not contain $$ or ; (SQL file tasks split on ;)")
    return f"CREATE OR REPLACE VIEW {schema}.{name}\nWITH METRICS\nLANGUAGE YAML\nAS $$\n{body}\n$$"


def deployStatements(manifest, views=None):
    """[(label, statement)] in dependency order: schema first, then each metric view."""
    schema = manifest["schema"]
    statements = [(SCHEMA_TASK, schemaStatement(schema))]
    for name, spec in manifest["views"].items():
        if views is None or name in views:
            statements.append((name, viewStatement(schema, name, spec)))
    return statements


def quoteIdent(name):
    return "`" + name.replace("`", "``") + "`"


def reportQuery(manifest, name):
    """Rebuild the legacy report through the metric view with MEASURE()."""
    report = manifest["views"][name]["report"]
    select = [quoteIdent(d) for d in report["dimensions"]]
    select += [f"MEASURE({quoteIdent(m)}) AS {quoteIdent(m)}" for m in report["measures"]]
    sql = f"SELECT {', '.join(select)}\nFROM {manifest['schema']}.{name}\nGROUP BY ALL"
    if report.get("order_by"):
        sql += "\nORDER BY " + ", ".join(report["order_by"])
    if report.get("limit"):
        sql += f"\nLIMIT {int(report['limit'])}"
    return sql


def reportOutput(unitName, units=None):
    units = units or loadYaml(UNITS_MANIFEST)["units"]
    unit = units.get(unitName)
    if unit is None:
        raise KeyError(f"unknown unit {unitName!r} in {UNITS_MANIFEST.relative_to(ROOT)}")
    for output in unit["outputs"]:
        if output["name"] == "report":
            return output
    raise KeyError(f"unit {unitName!r} declares no report output")


def renderJob(manifest):
    tasks = [{
        "task_key": SCHEMA_TASK,
        "max_retries": 1,
        "sql_task": {
            "file": {"path": f"../semantic/ddl/{SCHEMA_TASK}.sql", "source": "WORKSPACE"},
            "warehouse_id": "${var.warehouse_id}",
            "parameters": {"catalog": "${var.catalog}"},
        },
    }]
    for name in manifest["views"]:
        tasks.append({
            "task_key": name,
            "depends_on": [{"task_key": SCHEMA_TASK}],
            "max_retries": 1,
            "sql_task": {
                "file": {"path": f"../semantic/ddl/{name}.sql", "source": "WORKSPACE"},
                "warehouse_id": "${var.warehouse_id}",
                "parameters": {"catalog": "${var.catalog}"},
            },
        })
    job = {"resources": {"jobs": {"semantic_layer": {
        "name": "semantic_layer",
        "description": (
            "Creates the Unity Catalog semantic layer: ${var.catalog}.semantic metric views "
            "over the gold.* marts (databricks/semantic)."
        ),
        "max_concurrent_runs": 1,
        "tags": {"component": "semantic_layer"},
        "tasks": tasks,
    }}}}
    header = (
        "# GENERATED by tools/semantic_layer.py from databricks/semantic/manifest.yaml — do not edit.\n"
        "# Unity Catalog metric views are SQL objects, so they deploy as SQL tasks running the\n"
        "# CREATE OR REPLACE VIEW ... WITH METRICS files in databricks/semantic/ddl/ against\n"
        "# ${var.warehouse_id}, registered in ${var.catalog}.semantic. Unscheduled: run after\n"
        "# `databricks bundle deploy` with `databricks bundle run semantic_layer`.\n"
    )
    return header + yaml.safe_dump(job, sort_keys=False, width=120)


def renderFiles(manifest):
    files = {}
    for label, statement in deployStatements(manifest):
        source = (
            "databricks/semantic/manifest.yaml" if label == SCHEMA_TASK
            else f"databricks/semantic/{manifest['views'][label]['definition']}"
        )
        files[DDL_DIR / f"{label}.sql"] = DDL_HEADER.format(source=source) + statement + ";\n"
    files[JOB_RESOURCE] = renderJob(manifest)
    return files


def checkDefinitions(manifest, units=None):
    """Static checks: definitions parse, report columns exist and match the goldens."""
    errors = []
    units = units or loadYaml(UNITS_MANIFEST)["units"]
    for name, spec in manifest["views"].items():
        path = definitionPath(spec)
        if not path.exists():
            errors.append(f"{name}: {spec['definition']} does not exist")
            continue
        text = path.read_text()
        if "$$" in text or ";" in text:
            errors.append(f"{name}: definition must not contain $$ or ; (SQL file tasks split on ;)")
        definition = yaml.safe_load(text)
        if str(definition.get("version")) != "1.1":
            errors.append(f"{name}: definition version must be 1.1")
        if not str(definition.get("source", "")).startswith("gold."):
            errors.append(f"{name}: source must be a gold.* table")
        dims = [d["name"] for d in definition.get("dimensions") or []]
        measures = [m["name"] for m in definition.get("measures") or []]
        if not dims or not measures:
            errors.append(f"{name}: needs at least one dimension and one measure")
        if len(set(dims + measures)) != len(dims + measures):
            errors.append(f"{name}: dimension/measure names must be unique")
        report = spec["report"]
        for d in report["dimensions"]:
            if d not in dims:
                errors.append(f"{name}: report dimension {d!r} is not defined")
        for m in report["measures"]:
            if m not in measures:
                errors.append(f"{name}: report measure {m!r} is not defined")
        try:
            output = reportOutput(spec["unit"], units)
        except KeyError as exc:
            errors.append(f"{name}: {exc.args[0]}")
            continue
        meta = json.loads((ROOT / output["golden"]).with_suffix(".meta.json").read_text())
        goldenColumns = [c["name"] for c in meta["columns"]]
        reportColumns = report["dimensions"] + report["measures"]
        if sorted(reportColumns) != sorted(goldenColumns):
            errors.append(f"{name}: report columns {reportColumns} != {output['golden']} {goldenColumns}")
        if any(k not in report["dimensions"] for k in output["keys"]):
            errors.append(f"{name}: golden keys {output['keys']} must all be report dimensions")
    return errors


def generate(check=False):
    manifest = loadManifest()
    errors = checkDefinitions(manifest)
    files = renderFiles(manifest)
    expected = set(files)
    stale = [p for p, body in files.items() if not p.exists() or p.read_text() != body]
    orphans = sorted(p for p in DDL_DIR.glob("*.sql") if p not in expected) if DDL_DIR.exists() else []
    if errors:
        print("Semantic layer definitions are invalid:")
        print("\n".join(errors))
        return 1
    if check:
        if stale or orphans:
            print("Semantic layer files are stale; run python tools/semantic_layer.py generate:")
            print("\n".join(str(p.relative_to(ROOT)) for p in sorted(stale) + orphans))
            return 1
        print(f"Semantic layer checked: {len(manifest['views'])} metric views")
        return 0
    DDL_DIR.mkdir(parents=True, exist_ok=True)
    for path in orphans:
        path.unlink()
    for path, body in files.items():
        path.write_text(body)
    print(f"Semantic layer generated: {len(manifest['views'])} metric views, {len(files)} files")
    return 0


def approvedCatalog(catalog):
    approved = set(APPROVED_CATALOGS)
    if ALLOWED_TARGETS.exists():
        approved &= set(json.loads(ALLOWED_TARGETS.read_text()).get("catalogs", approved))
    if catalog not in approved:
        raise SystemExit(f"catalog {catalog!r} is not an approved migration catalog {sorted(approved)}")
    return catalog


def deploy(db, views=None, manifest=None):
    manifest = manifest or loadManifest()
    approvedCatalog(db.catalog)
    unknown = set(views or []) - set(manifest["views"])
    if unknown:
        raise SystemExit(f"unknown metric views: {sorted(unknown)}")
    for label, statement in deployStatements(manifest, views):
        db.run(statement)
        print(f"  created {db.catalog}.{manifest['schema']}.{label}" if label != SCHEMA_TASK
              else f"  schema {db.catalog}.{manifest['schema']} ready")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)
    gen = sub.add_parser("generate")
    gen.add_argument("--check", action="store_true")
    dep = sub.add_parser("deploy")
    dep.add_argument("--view", action="append", help="limit to one metric view (repeatable)")
    args = parser.parse_args()
    if args.command == "generate":
        return generate(check=args.check)
    deploy(DbSql(), views=args.view)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
